
!////////////////////////////////////////////////////////////////////////
!! Abbrev words for Fortran (Last updated: 2014-9-2)

#ifndef __abbrev_inc__
#define __abbrev_inc__

#include "_abbrev_.inc"

#define  Bool         logical
#define  Char         character
#define  Int          integer
#define  Dble         real(8)
#define  Dcmplx       complex(8)
#define  Dcomplex     complex(8)
#define  sub          subroutine
#define  endsub       end subroutine
#define  endfunc      end function
#define  endmod       end module
#define  put          write(6,*)
#define  printf(x)    write(6,x)
#define  using(x)     use x, only:

#endif /* __abbrev_inc__ */
!////////////////////////////////////////////////////////////////////////

